name: caller
on:
  workflow_dispatch:
  push:
jobs:
  deploy:
    permissions:
      contents: write
      id-token: write
    uses: hmz-latest-new2/.github/.github/workflows/reusable.yml@main
    secrets:
      DEPLOY_SECRET: ${{ secrets.VICTIM_SECRET }}
